const listOfDefaultContributionTypes = [
  "a11y",
  "audio",
  "blog",
  "bug",
  "business",
  "code",
  "content",
  "data",
  "design",
  "doc",
  "eventOrganizing",
  "example",
  "financial",
  "fundingFinding",
  "ideas",
  "infra",
  "maintenance",
  "mentoring",
  "platform",
  "plugin",
  "projectManagement",
  "question",
  "research",
  "review",
  "security",
  "talk",
  "test",
  "tool",
  "translation",
  "tutorial",
  "userTesting",
  "video",
  "promotion",
];

module.exports = listOfDefaultContributionTypes;
